Check dataset, model and property names.
atviriduomenys/spinta pull request #327
Opened 2022-11-17 10:21 UTC by Gediminas-msc

2022-11-17 10:24 UTC, Gediminas-msc commented
Could you explain what this means: "Check if dataset, model and property names uses only allowed symbols."?

2022-11-28 07:58 UTC, sirex requested changes

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +import re
Standard library imports always goes to the top, see [PEP-8](https://pep8.org/#imports).

2022-11-28 07:58 UTC, sirex commented on spinta/cli/config.py
> +    names: bool = Option(False, '--names', help="To check dataset, model and property names"),
There is not need to add `'--names'`, it is added by default.

2022-11-28 07:58 UTC, sirex commented on spinta/core/config.py
> +    names: bool = False,
Maybe change this to `check_names`? Because `names` is too ambiguous.

2022-11-28 07:58 UTC, sirex commented on spinta/core/config.py
> +        config['names'] = names
Same here, change to `check_names`?

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +    if rc.get('names'):
```suggestion
    config: Config = context.get('config')

    if config.check_names:
```

All configuration parameters should be set on top of `config`.

See: https://github.com/atviriduomenys/spinta/blob/master/spinta/types/config.py

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +        is_lowercase = len([i for i in name if i.islower()] + re.findall('/', name)) == len(name)
Can you check name with only regexps? A one regex, like this:

    [a-z][a-z0-1_]*(/[a-z][a-z0-1_]*)*

Should check whole dataset name.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +            raise Exception(f'Dataset name {name} is not correct.')
Create a custom class in `spinta/exceptions.py` called `InvalidName`, which should extend `UserError`.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +        for name, model in models.items():
Model checks should go to `spinta/types/model.py` on `check[Context, Model]` command method.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +                is_uppercase = name.upper() == name
Use regular expression.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +                    raise Exception(f'Model name {name} is not correct.')
Use `InvalidName` exception from `spinta/exceptions.py`.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +            for prop_name, prop in model.properties.items():
Properties should be checked in `spinta/types/model.py` on `check[Context, Property]` command method.

2022-11-28 07:58 UTC, sirex commented on spinta/datasets/commands/check.py
> +                if re.findall(r'^[A-Z]\w*$', prop_name):
Use precompiled regular expressions and the regular expression is not correct, please add tests to check if it really works.

2022-11-28 13:16 UTC, sirex commented on spinta/datasets/commands/check.py
> +        is_lowercase = len([i for i in name if i.islower()] + re.findall('/', name)) == len(name)
https://regexkit.com/python-regex

2022-12-02 09:21 UTC, sirex requested changes

2022-12-02 09:21 UTC, sirex commented on spinta/cli/config.py
> +    names: bool = Option(False, help="To check dataset, model and property names"),
```suggestion
    check_names: bool = Option(False, help="To check dataset, model and property names"),
```

2022-12-02 09:21 UTC, sirex commented on spinta/core/config.py
> +        config['check.names'] = check_names
Also add this to `config.yml`.

2022-12-02 09:21 UTC, sirex commented on spinta/datasets/commands/check.py
> +        is_lowercase = re.compile(r'^[a-z0-1_]*(/[a-z0-1_]*)+$')
Move this to module level. Also, dataset name can't start with `_`, this is for reserved names. There are some reserved names, but these names should be listed and checked against know reserved names.

Also each part separated with `/` in dataset name should start with `[a-z]` and only then, second ant other symbols can be `[a-z0-9_]`. Dataset name can't start with `/`, so in your regexp first block should end with `+` and second with `*`.

2022-12-02 09:21 UTC, sirex commented on spinta/datasets/commands/check.py
> +        if is_lowercase.match(name) is None or name.startswith('/') or name.endswith('/') or name.count('//'):
All checks should be done only with regexes. There is no need to manually check slashes.

2022-12-02 09:21 UTC, sirex commented on spinta/types/helpers.py
> +            camel_case = re.compile(r'[A-Z][a-z]+')
Move compile to module level. Also names like `CityStreet` should be allowed.

2022-12-02 09:21 UTC, sirex commented on spinta/types/helpers.py
> +        if not name.startswith('_'):
Check all reserved names against a list of allowed reserved names.

2022-12-02 09:21 UTC, sirex commented on spinta/types/helpers.py
> +            snake_case = re.compile(r'[a-z0-1_]+')
Property names can't start with `_` or `[0-9]`.

2022-12-02 14:18 UTC, sirex requested changes

2022-12-02 14:18 UTC, sirex commented on spinta/config.yml
> +    check_names:
```suggestion
    names:
```

2022-12-02 14:18 UTC, sirex commented on spinta/core/config.py
> +    check_names: bool = False,
```suggestion
    check_names: Optional[bool] = None,
```

This option can be set via environment variables or other means, so we only should set this, if it is given via command line argument.

2022-12-02 14:18 UTC, sirex commented on spinta/core/config.py
> +        config['check.names'] = check_names
Do not set this, if `check_names` is `None`.

2022-12-02 14:18 UTC, sirex commented on spinta/cli/config.py
> +    check_names: bool = Option(False, help="To check dataset, model and property names"),
This should be `None` by default.

2022-12-02 14:18 UTC, sirex commented on spinta/types/helpers.py
> +snake_case = re.compile(r'^[a-z][a-z0-9]+(_[a-z0-9]+)*$')
Add tests.

2022-12-12 14:31 UTC, sirex requested changes
Please add tests, and test datasets, model, property names and error messages, add test if single letter names are allowed, add tests for invalid cases.

2022-12-12 14:31 UTC, sirex commented on spinta/types/helpers.py
> +            if upper_camel_case.match(name) is None:
Check model name and namespace separately. For example:

    a/b/c/Model

Here `a/b/c` is a namespace and should be checked with `check[Context, Namespace]`, `Model` is a model name and should be checked separately with `check[Context, Model]`.

2023-11-24 13:57 UTC, merged