364 replace frictionless-py with sqlachemy
atviriduomenys/spinta pull request #404
Opened 2023-03-24 08:51 UTC by adp-atea

2023-04-04 07:34 UTC, adp-atea commented
There are failing tests, that I'm not sure how to fix. I commented them out for now. 

One problem is that some use sqldump as resource and we try to get manifest type from this resource ([here](https://github.com/atviriduomenys/spinta/blob/61cc3d321938770c903bf7d282d7c1d8111907f8/spinta/cli/inspect.py#L85)), but there is no sqldump manifest, there's only sqldump backend.

Another problem is when we have existing manifest and there's database related to it and added to the context ([example](https://github.com/atviriduomenys/spinta/blob/61cc3d321938770c903bf7d282d7c1d8111907f8/tests/test_inspect.py#L352))
but it is not added as resource with -r to command. In this case when manifest is loaded, it's loaded only from the file and related database is not taken into account.

2023-04-14 09:43 UTC, sirex requested changes
When I run

    poetry run spinta --tb=native inspect -r sql sqlite:///$BASEDIR/db.sqlite -o $BASEDIR/manifest.csv

I get following error:

```python
Traceback (most recent call last):
  File "spinta/cli/inspect.py", line 65, in inspect
    store = load_manifest(context, ensure_config_dir=True)
  File "spinta/cli/helpers/store.py", line 99, in load_manifest
    store = load_store(
  File "spinta/cli/helpers/store.py", line 85, in load_store
    commands.load(context, store)
  File "spinta/types/store.py", line 50, in load
    manifest = create_manifest(context, store, manifest)
  File "spinta/manifests/helpers.py", line 68, in create_manifest
    Manifest_ = config.components['manifests'][mtype]
KeyError: 'memory'
```

You need to also add `memory` manifest, which would be responsible only for loading other manifests.

See: https://spinta.readthedocs.io/en/latest/contrib/manifests.html#adding-new-manifest-type

For `load` command you need to only add:

```python
    if load_internal:
         target = into or manifest
         if '_schema' not in target.models:
             store = context.get('store')
             commands.load(context, store.internal, into=target)

     for source in manifest.sync:
         commands.load(
             context, source,
             into=into or manifest,
             freezed=freezed,
             rename_duplicates=rename_duplicates,
             load_internal=load_internal,
         )
```

2023-05-08 09:16 UTC, sirex requested changes

2023-05-08 09:16 UTC, sirex commented on notes/cli/inspect.sh
> +# FIXME: `continent` type was lost, types specified in manifest table should be preserved.
Property types specified in manifest file, should be preserved even if type in data source has changed. For example here, foreign key was not specified in data source, but it was specified in manifest file, so after updating manifest from source, we should preserve foreign key in manifest file.

2023-05-09 07:19 UTC, sirex approved these changes

2023-05-09 07:19 UTC, sirex commented on spinta/cli/inspect.py
> +        raise Exception(f"\'{priority}\' priority doesnt not exist, there can only be \'manifest\' or \'external\'")
I think, this should not be an exception, but a simple error message, printed with `print`.

2023-05-09 07:19 UTC, sirex commented on spinta/cli/inspect.py
> +    if result.__contains__("@"):
```suggestion
    if "@" in result:
```

2023-05-09 07:19 UTC, sirex commented on spinta/cli/inspect.py
> +    if dsn.__contains__("@"):
```suggestion
    if "@" in dsn:
```

2023-05-09 08:05 UTC, merged