217, 256, 268 Add xml, json backends, support for tabular(sep: ";")
atviriduomenys/spinta pull request #456
Opened 2023-05-22 10:10 UTC by adp-atea

2023-07-26 09:07 UTC, sirex requested changes

2023-07-26 09:07 UTC, sirex commented on notes/datasets/xml.sh
> +http GET "$SERVER/$DATASET/SeimoKadencija"
I get following error, when trying to read XML:

```python
Traceback (most recent call last):
  File "spinta/api.py", line 95, in homepage
    return await create_http_response(context, params, request)
  File "spinta/utils/response.py", line 153, in create_http_response
    return await commands.getall(
  File "spinta/commands/read.py", line 125, in getall
    return render(context, request, model, params, rows, action=action)
  File "spinta/renderer.py", line 23, in render
    return commands.render(
  File "multipledispatch/dispatcher.py", line 278, in __call__
    return func(*args, **kwargs)
  File "spinta/formats/json/commands.py", line 25, in render
    return _render(
  File "spinta/formats/json/commands.py", line 52, in _render
    aiter(peek_and_stream(fmt(data))),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spinta/utils/response.py", line 223, in peek_and_stream
    peek = list(itertools.islice(stream, 2))
  File "spinta/formats/json/components.py", line 16, in __call__
    for i, row in enumerate(data):
  File "spinta/accesslog/__init__.py", line 162, in log_response
    for row in rows:
  File "spinta/commands/read.py", line 110, in <genexpr>
    rows = (
  File "spinta/datasets/backends/dataframe/commands/read.py", line 398, in getall
    yield from _dask_get_all(context, query, df, backend, model, builder)
  File "spinta/datasets/backends/dataframe/commands/read.py", line 435, in _dask_get_all
    for i, row in qry.iterrows():
  File "spinta/datasets/backends/dataframe/commands/read.py", line 298, in _get_data_xml
    return _parse_xml(f.raw, source, model_props)
  File "spinta/datasets/backends/dataframe/commands/read.py", line 138, in _parse_xml
    for action, elem in etree.iterparse(data, events=('start', 'end'), remove_blank_text=True):
  File "src/lxml/iterparse.pxi", line 210, in lxml.etree.iterparse.__next__
  File "src/lxml/iterparse.pxi", line 195, in lxml.etree.iterparse.__next__
  File "src/lxml/iterparse.pxi", line 226, in lxml.etree.iterparse._read_more_events
  File "src/lxml/parser.pxi", line 1395, in lxml.etree._FeedParser.close
  File "<string>", line 0
lxml.etree.XMLSyntaxError: no element found
```

2023-08-03 12:06 UTC, sirex requested changes

2023-10-24 07:03 UTC, sirex approved these changes
I suggest to merge this and fix remaining issues with another pull request.

2023-10-24 07:33 UTC, adp-atea commented on notes/datasets/json.sh
> +#        means it is in UTC timezone. Please handle timezone-aware dates correctly.
will be fixed with separate PR

2023-10-24 07:33 UTC, adp-atea commented on notes/datasets/json.sh
> +#        page url as described with `url` param.
will be fixed with separate PR

2023-10-24 07:33 UTC, adp-atea commented on notes/datasets/json.sh
> +# FIXME: Probably issue with the pagination
will be fixed with separate PR

2023-10-24 08:39 UTC, merged