315 add support for wsdlsoap data source
atviriduomenys/spinta pull request #614
Opened 2024-05-20 12:18 UTC by karina-klinkeviciute

2024-05-28 14:35 UTC, sirex requested changes

2024-05-28 15:00 UTC, karina-klinkeviciute commented on spinta/datasets/backends/dataframe/commands/read.py
> +        if e.context["name"] in ('eq', ):
o kitais atvejais negali būti, kad kažkaip kitaip turėtų veikti ir kad resolveryje kartais gali būti ir kitaip? Jei ne, tai tada tikrai erta perkelti į resolverį.

2024-05-28 15:53 UTC, karina-klinkeviciute commented on spinta/datasets/backends/dataframe/commands/read.py
> +    # }
o šitą pavyzdį palikti, ar irgi geriau išimti?
    # Example:
    # Get.GetPort.GetPortType.GetData

2024-05-29 12:23 UTC, karina-klinkeviciute commented on spinta/datasets/backends/dataframe/commands/read.py
> +            raise SoapServiceError("Soap service does not exist")
perkėliau, tikiuosi teisingai :)

2024-05-29 13:54 UTC, karina-klinkeviciute commented on spinta/datasets/backends/dataframe/commands/read.py
> +        if e.context["name"] in ('eq', ):
Perkėliau čia: https://github.com/atviriduomenys/spinta/pull/614/files#diff-e2988eba5000b476682036202d4e8e6d4d5a6ee866f670965599745cafcf5719R186

2025-09-16 17:24 UTC, closed without merging