513 getone for external sql backend
atviriduomenys/spinta pull request #616
Opened 2024-05-23 14:44 UTC by karina-klinkeviciute

2024-05-24 06:00 UTC, sirex requested changes
Reikėtu sukurti užduotis `getone` įgyvendinimui ir kitiems backendams. Taip pat paminėjau dar kelias vietas komentaruose, kur reikėtu sukurti užduotis.

O šiai patrodo gerai, tik reikėtu atnaujinti notes ir nenaudoti QueryBuilder.

2024-05-24 06:22 UTC, karina-klinkeviciute commented on spinta/datasets/backends/sql/commands/read.py
> +    query = Expr('eq', pk, _id)
hmm, šito ir kode nepadariau, kad veiktų. Pasigilinsiu, kaip čia reiktų daryti ir pabandysiu pakeisti, ir tada pakeisiu ir testą. Kaip apsirašo tai manifeste, per kablelį ar atskiros eilutės?

2024-05-24 06:22 UTC, karina-klinkeviciute commented on spinta/datasets/backends/sql/commands/read.py
> +        '_id': id_
sukursiu užduotį

2024-05-24 16:08 UTC, karina-klinkeviciute commented
> Reikėtu sukurti užduotis `getone` įgyvendinimui ir kitiems backendams. 

sukūriau užduotis `json`, `xml`, `csv` ir `soap` backendams. Ar reikia dar kam nors?

#617 
#618 
#619 
#620

2024-05-24 16:14 UTC, karina-klinkeviciute commented on spinta/datasets/backends/sql/commands/read.py
> +        '_id': id_
sukūriau #621

2024-05-24 16:23 UTC, karina-klinkeviciute commented on notes/datasets/sql/getone.sh
> +#| }
atnaujinau

2024-05-28 14:28 UTC, sirex approved these changes

2024-05-29 16:59 UTC, karina-klinkeviciute commented on spinta/datasets/backends/sql/commands/read.py
> +        )
čia kaip kalbėjom, kad gal tiesiog teste neprideda `keymap`, tai kai nuimu čia `keymap` pridėjimą į `context`, tai ir paleidus spintą pilnam veikimui, irgi gaunu tą pačią klaidą:

"Unknown context variable 'keymap.default'."

2024-06-13 12:42 UTC, merged

2024-06-14 04:50 UTC, sirex commented on spinta/datasets/backends/sql/commands/read.py
> +        )
Gali būti ir taip, kaip dabar padarei.