666 add keymap sync command - 0.1
atviriduomenys/spinta pull request #968
Opened 2024-11-22 08:47 UTC by Tadas-Stankevicius

2024-11-22 09:17 UTC, JustinasKen commented on spinta/datasets/keymaps/sync.py
> +                if row['_op'] == 'insert' and not dry_run:
Neverta būtų iškelti`dry_run` patikrinimą į pradžią, tai yra, jei `counters` nebus skaičiuojami (kaip dabar padarei), tada tiesiog pakeisti if check į `if not dry_run and status_code == 200`, nebent tikslas, kad prasisuktu counters, tada reiktų keisti šiek tiek logiką ?

2024-11-22 09:17 UTC, JustinasKen commented on tests/cli/test_keymap.py
> +            request.addfinalizer(lambda: remote.app.context.wipe_all())
reiktu patikrinti ar ši vieta nepakenkia kitiems testams

2024-11-22 12:44 UTC, Tadas-Stankevicius commented on tests/cli/test_keymap.py
> +            request.addfinalizer(lambda: remote.app.context.wipe_all())
pakeistas taikymas, neatrodo, kad kiti testai paveikti

2024-11-25 07:31 UTC, JustinasKen requested changes

2024-11-25 07:31 UTC, JustinasKen commented on spinta/cli/keymap.py
> +def _attach_backends(context: Context, store: Store, manifest: Manifest) -> None:
Kad nereiktu dublikuoti kodą (`push` ir `sync` CLI), reiktų iškelti `_attach_backends` ir `_attach_keymaps` prie helpers (`store.py` arba `manifest.py`)

2024-11-25 07:31 UTC, JustinasKen commented on spinta/commands/__init__.py
> +
Kur yra naudojama `keymap()` command ?

2024-11-25 07:54 UTC, Tadas-Stankevicius commented on spinta/commands/__init__.py
> +
Nereikalinga

2024-11-25 07:55 UTC, Tadas-Stankevicius commented on spinta/cli/keymap.py
> +def _attach_backends(context: Context, store: Store, manifest: Manifest) -> None:
Iškelta prie store.py

2024-11-25 08:23 UTC, merged